---
sdkversion: 3.5.2
name: RhoConnect Monitor
version: 1.0
vendor: spritle
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator6.0
  codesignidentity: ! 'iPhone Developer: Balaji D Loganathan (TB3F5AV4X6)'
  entitlements: ''
  BundleURLScheme: rcmon
  BundleIdentifier: com.spritle.rhoconnectmon
android:
  version: 2.1
  android_title: 0
extensions:
- json
sdk: /Users/balajidl/.rvm/gems/ruby-1.9.3-p327/gems/rhodes-3.5.1.12
